### ISSUE TITLE
Unable to build slash

### ISSUE THREAD

**Issue by piotr-yuxuan** [slash-hq/slash#21]
Hello, that app seems promissing! I attempted to give it a try but stumble across a build error.

```
$ brew install https://raw.githubusercontent.com/slash-hq/slash/master/slash.rb
######################################################################## 100.0%
==> Downloading https://github.com/slash-hq/slash/archive/0.1.0.tar.gz
Already downloaded: /Users/piotr-yuxuan/Library/Caches/Homebrew/slash-0.1.0.tar.gz
==> xcodebuild -workspace slash.xcodeproj/project.xcworkspace -derivedDataPath prefix.to_s -configuration Release -scheme slash SYMROOT=/usr/local/Cellar/slash/0.1.0/Build
Last 15 lines from /Users/piotr-yuxuan/Library/Logs/Homebrew/slash/01.xcodebuild:
                                ^
/tmp/slash-20170628-46970-rh6n3g/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^
/tmp/slash-20170628-46970-rh6n3g/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Do not report this issue to Homebrew/brew or Homebrew/core!
```

In case you might find this useful, I provide you with some description of my system:
```
$ uname -a
Darwin work 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

$ swift --version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

$ python --version
Python 2.7.13

$ brew --version
Homebrew 1.2.3
Homebrew/homebrew-core (git revision ec3bc; last commit 2017-06-28)

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libzbar.la
```

and finally, I hope you may find this useful but I apology for the great length of this code snippet:

```
$ brew install -vd https://raw.githubusercontent.com/slash-hq/slash/master/slash.rb
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.3 (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail https://raw.githubusercontent.com/slash-hq/slash/master/slash.rb -o /Users/piotr-yuxuan/Library/Caches/Homebrew/Formula/slash.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   564  100   564    0     0   1868      0 --:--:-- --:--:-- --:--:--  1873
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromUrlLoader): loading /Users/piotr-yuxuan/Library/Caches/Homebrew/Formula/slash.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /Users/piotr-yuxuan/Library/Caches/Homebrew/Formula/slash.rb
==> Downloading https://github.com/slash-hq/slash/archive/0.1.0.tar.gz
Already downloaded: /Users/piotr-yuxuan/Library/Caches/Homebrew/slash-0.1.0.tar.gz
==> Verifying slash-0.1.0.tar.gz checksum
tar xzf /Users/piotr-yuxuan/Library/Caches/Homebrew/slash-0.1.0.tar.gz
==> xcodebuild -workspace slash.xcodeproj/project.xcworkspace -derivedDataPath prefix.to_s -configuration Release -scheme slash SYMROOT=/usr/local/Cellar/slash/0.1.0/Build
User defaults from command line:
    IDEDerivedDataPathOverride = /private/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s

Build settings from command line:
    SYMROOT = /usr/local/Cellar/slash/0.1.0/Build

=== BUILD TARGET slash OF PROJECT slash WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-generated-files.hmap
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-all-non-framework-target-headers.hmap
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-project-headers.hmap
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/swift-overrides.hmap
/bin/mkdir -p /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash.LinkFileList
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash.hmap
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-all-target-headers.hmap
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash-OutputFileMap.json
write-file /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-own-target-headers.hmap

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name slash -O -whole-module-optimization -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -target x86_64-apple-macosx10.11 -g -module-cache-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/ModuleCache -Xfrontend -serialize-debugging-options -I /usr/local/Cellar/slash/0.1.0/Build/Release -F /usr/local/Cellar/slash/0.1.0/Build/Release -c -num-threads 8 /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackGroup.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Server.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/UserInputView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/MessagesListView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TLSSocket.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Utils.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackWebClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackIM.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackChannel.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackUser.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/CrashReporter.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackMessage.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/main.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackEvent.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/WebSocketClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackAdapter.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/R.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/ChannelsListView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackEmojiDecoder.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Application.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackOAuth2.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackContext.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackRealTimeClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackTeam.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TerminalDevice.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TerminalCanvas.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TextLayout.swift -output-file-map /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash.swiftmodule -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/swift-overrides.hmap -Xcc -iquote -Xcc /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-generated-files.hmap -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-own-target-headers.hmap -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-all-target-headers.hmap -Xcc -iquote -Xcc /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-project-headers.hmap -Xcc -I/usr/local/Cellar/slash/0.1.0/Build/Release/include -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/DerivedSources/x86_64 -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/DerivedSources -emit-objc-header -emit-objc-header-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash-Swift.h -Xcc -working-directory/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0

CompileSwift normal x86_64
    cd /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackGroup.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Server.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/UserInputView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/MessagesListView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TLSSocket.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Utils.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackWebClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackIM.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackChannel.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackUser.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/CrashReporter.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackMessage.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/main.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackEvent.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/WebSocketClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackAdapter.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/R.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/ChannelsListView.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackEmojiDecoder.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Application.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackOAuth2.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackContext.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackRealTimeClient.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackTeam.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TerminalDevice.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TerminalCanvas.swift /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/TextLayout.swift -target x86_64-apple-macosx10.11 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I /usr/local/Cellar/slash/0.1.0/Build/Release -F /usr/local/Cellar/slash/0.1.0/Build/Release -g -module-cache-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/ModuleCache -serialize-debugging-options -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/swift-overrides.hmap -Xcc -iquote -Xcc /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-generated-files.hmap -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-own-target-headers.hmap -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-all-target-headers.hmap -Xcc -iquote -Xcc /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/slash-project-headers.hmap -Xcc -I/usr/local/Cellar/slash/0.1.0/Build/Release/include -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/DerivedSources/x86_64 -Xcc -I/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/DerivedSources -Xcc -working-directory/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0 -emit-module-doc-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash.swiftdoc -serialize-diagnostics-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackGroup.dia -O -module-name slash -emit-module-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash.swiftmodule -emit-objc-header-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/slash-Swift.h -emit-dependencies-path /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackGroup.d -num-threads 8 -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackGroup.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/Server.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/UserInputView.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/MessagesListView.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/TLSSocket.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/Utils.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackWebClient.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackIM.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackChannel.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackUser.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/CrashReporter.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackMessage.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/main.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackEvent.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/WebSocketClient.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackAdapter.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/R.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/ChannelsListView.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackEmojiDecoder.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/Application.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackOAuth2.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackContext.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackRealTimeClient.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/SlackTeam.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/TerminalDevice.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/TerminalCanvas.o -o /tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/prefix.to_s/Build/Intermediates/slash.build/Release/slash.build/Objects-normal/x86_64/TextLayout.o
/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/Server.swift:326:70: error: @escaping attribute may only be used in function parameter position
    func serve(_ callback: @escaping ((request: Request, responder: @escaping ((Response) -> Void))) -> Void) throws {
                                                                    ~^~~~~~~~~

/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackWebClient.swift:71:33: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
            try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                ^
/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^
/tmp/slash-20170628-75446-5xs1ox/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: xcodebuild -workspace slash.xcodeproj/project.xcworkspace -derivedDataPath prefix.to_s -configuration Release -scheme slash SYMROOT=/usr/local/Cellar/slash/0.1.0/Build
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1859:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1797:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1797:in `system'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:135:in `xcodebuild'
/Users/piotr-yuxuan/Library/Caches/Homebrew/Formula/slash.rb:9:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:137:in `block in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1148:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1960:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1939:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1143:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/slash-20170628-75446-5xs1ox

==> Formula
Path: /Users/piotr-yuxuan/Library/Caches/Homebrew/Formula/slash.rb
==> Configuration
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec3bc916e9b9b8855f9feac5410832fcdeffad0e
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.8.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_91
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin

Error: slash 0.1.0 did not build
Logs:
     /Users/piotr-yuxuan/Library/Logs/Homebrew/slash/00.options.out
     /Users/piotr-yuxuan/Library/Logs/Homebrew/slash/01.xcodebuild
Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by zachschultz** [comment]
I have this same issue

**Comment by niklasberglund** [comment]
This issue has been fixed in commit ef9207655d7aa80edcc08e428b6c6433231b3e86. If you download the latest source code from the repo instead of the 0.1.0 source code you shouldn't run into this issue.

**Comment by rafaelsales** [comment]
Just had this one:
```
==> Downloading from https://codeload.github.com/slash-hq/slash/tar.gz/0.1.0
######################################################################## 100.0%
==> xcodebuild -workspace slash.xcodeproj/project.xcworkspace -derivedDataPath prefix.to_s -configuration Release -scheme slash SYMROOT=/usr/local/Cellar/slash/0.1.0/Build
Last 15 lines from /Users/rafaelsales/Library/Logs/Homebrew/slash/01.xcodebuild:
                                ^
/tmp/slash-20170815-2772-1p90xgi/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^
/tmp/slash-20170815-2772-1p90xgi/slash-0.1.0/Sources/SlackOAuth2.swift:62:45: warning: 'sendSynchronousRequest(_:returning:)' was deprecated in OS X 10.11: Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
                        try NSURLConnection.sendSynchronousRequest(URLRequest(url: url), returning: nil))
                                            ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by adius** [comment]
How about releasing a new version with the fixes, or updating the readme that the brew install is not working anymore

**Comment by piotr-yuxuan** [comment]
Closing, as it no longer works indeed. Anyway, thanks for your replies!
